### ISSUE TITLE
Cannot find gPRC. Colocn build failure

### ISSUE THREAD

**Issue by alexsmau** [Blickfeld/blickfeld_qb2_ros2_driver#1]
The module fails to build because it cannot find gRPC even though I have done the install commands in the prerequisites instructions. I decided instead to build gRPC from source as, on their website, this was the preferred method. This got me further, but still it failed.
The solution was to add the following lines in the CMakeLists.txt file:

find_package(Protobuf REQUIRED)
find_package(gRPC REQUIRED PATH /home/user/ros/third_party_sw/grpc)

Note: adding just the second line does not work.

Is there a better way of doing this? If not, can you add the two lines so I don't have to fork the code?

**Comment by Fabian-Wagner-BF** [comment]
I just send you an email to work on this issue.

**Comment by Fabian-Wagner-BF** [comment]
The problem was caused by the missing dependency which is not described in our current documentation.
Installing the package "protobuf-compiler-grpc" before building, will fix the issue.
`sudo apt install -y protobuf-compiler-grpc`

Will be added to the documentation.
