### ISSUE TITLE
Failing to connect to Qb2 device

### ISSUE THREAD

**Issue by cynosure4sure** [Blickfeld/blickfeld_qb2_ros2_driver#2]
Hi!

I am trying to get pointcloud from the lidar but the ros2 driver fails to connect to the device giving the following error:

`[blickfeld_qb2_driver]: Failed to connect to Qb2: qb2-xxxxxxxxx , due to: Connection to Qb2 device 'qb2-xxxxxxxxx:50051' failed (insecure pre-handshake serial number fetch): DNS resolution failed.`

In the blickfeld_qb2_ros2_driver.launch.py file I tried providing both the IP address and qb2-xxxxxxxxx host name as parameters but get the same error for both.

Using the IP address I can ping the device and in the WebUI I can access the device and also get a pointcloud.

Any advice would be helpful. 

Thank you

**Comment by cynosure4sure** [comment]
Updated: was using the host IP instead of using device IP. Using device IP works however the hostname does not work

**Comment by ToriSR** [comment]
I'm having the exact same problem, where I can ping the device and access via WebUI, but the ros2 driver is failing to connect (colcon build was successful). Could you explain me what exactly you changed to solve the problem? I don't understand where you get the device IP and where I should put it in. Thank you in advance!
