### ISSUE TITLE
Failed to connect to Qb2 due to: Connection to Qb2 device failed. Network failure..

### ISSUE THREAD

**Issue by ToriSR** [Blickfeld/blickfeld_qb2_ros2_driver#3]
Hi,

I am trying to launch my Qb2 lidar using ros2 launch file and view the Point Cloud visualization using rviz2. I followed the documentation of the manufacturer, installing dependencies, structured the workspace properly. Still, after I built the workspace and launch it using command ` ros2 launch blickfeld_qb2_ros2_driver blickfeld_qb2_ros2_driver.launch.py`, I got this error:

```[component_container-1] [WARN] [1717264468.278474163] [blickfeld_qb2_driver]: Failed to connect to Qb2: 192.168.26.254 , due to: Connection to Qb2 device '192.168.26.254:51744' failed. Network failure..
[component_container-1] [WARN] [1717264468.278646200] [blickfeld_qb2_driver]: Failed to read a point cloud from stream, Qb2: 192.168.26.254 is disconnected!
```

The documentation mentioned that the user is required to provide a valid address for connection, as no default value is available. However, it didn't specify where exactly or how to do that. I assume that it means to change the `fdqn` parameter to the ip address `192.168.26.254` of my host device that is receiving the sensor in the launch file. Originally, that parameter was qb2 by default. Apart from that, I didn't change anything in the launch file (should I change something?).

I have verified that it is not hardware issue since I can view the point cloud in on my web browser at `192.168.26.26`, and Wireshark also registers constant communication between my computer and the lidar. There is also nothing when googled.

I don't know what to do next. Can someone please help?

**Comment by Fabian-Wagner-BF** [comment]
Hi,

which Version of the driver did you install and which ROS Distro are you using?

On a first glance it looks that you took the wrong IP Address or did not specify it in the launch file.
Please try to start the driver with the following command:
`ros2 component standalone blickfeld_qb2_ros2_driver blickfeld::ros_interop::Qb2Driver -p fqdn:="IP-Address of your Qb2"`

f.e. with the fallback IP
`ros2 component standalone blickfeld_qb2_ros2_driver blickfeld::ros_interop::Qb2Driver -p fqdn:="192.168.26.26"`

You can get the IP Address of your device by pinging it:
`ping qb2-<serialnumber>`

f.e. 
`ping qb2-mclpobiac`

alternatively you can modify the launch file:

1. source your workspace with
`source ~/colcon_workspace_Qb2/install/setup.bash`

2. navigate to your launch file and open it
![image](https://github.com/Blickfeld/blickfeld_qb2_ros2_driver/assets/144440369/b53e1c90-89f4-44c1-ba8e-e53be4aefad9)

3. modify the blickfeld_qb2_ros2_driver.launch.py launch file with the IP-Address of your device
![image](https://github.com/Blickfeld/blickfeld_qb2_ros2_driver/assets/144440369/a1e6e599-e277-48b1-b9de-a581a85ab1ed)

**Comment by ToriSR** [comment]
Specifying the ip address solved the issue, thanks a lot!
